### ISSUE TITLE
[enhacement] cover container deployment for environments require proxy 

### ISSUE THREAD

**Issue by 00-eight** [dell/iDRAC-Telemetry-Reference-Tools#5]
It would be helpful to include reference for environments which require a proxy given it has to be defined in many places. 

[Docker Daemon](https://docs.docker.com/config/daemon/systemd/#httphttps-proxy) required to pull images 
[Docker Client](https://docs.docker.com/network/proxy/#configure-the-docker-client) required for container images that need to pull down imports 
- ***note*** noProxy option should also be specified so intra container communication does not attempt to hit proxy. 

Additionally docker-compose files could add define for ***ports*** to the containers 
```
  kib01:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kib01
    depends_on: {"es01": {"condition": "service_healthy"}}
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic
    ports:
      - 5601:5601
 ```
